---
abstract: 'Read active Samba server data from smbstatus'
author:
  - 'Louis Erickson, C<< <laufeyjarson at laufeyjarson.com> >>'
  - 'Louis Erickson <laufeyjarson@laufeyjarson.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Samba-Smbstatus
no_index:
  directory:
    - inc
    - t
requires:
  Moo: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Samba-Smbstatus
  homepage: http://blog.laufeyjarson.com
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/laufeyjarson/samba-smbstatus.git
version: '0.01'
